"""evidence items

Revision ID: 06b0821216ab
Revises: 54ac86ee0748
Create Date: 2026-02-10 14:05:49.498355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b0821216ab'
down_revision: Union[str, Sequence[str], None] = '54ac86ee0748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('storage_key', sa.String(length=600), nullable=True),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_evidence_items_content_hash'), 'evidence_items', ['content_hash'], unique=False)
    op.create_index(op.f('ix_evidence_items_tenant_id'), 'evidence_items', ['tenant_id'], unique=False)
    op.create_index('ix_evidence_tenant_created', 'evidence_items', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_evidence_tenant_title', 'evidence_items', ['tenant_id', 'title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evidence_tenant_title', table_name='evidence_items')
    op.drop_index('ix_evidence_tenant_created', table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_tenant_id'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_content_hash'), table_name='evidence_items')
    op.drop_table('evidence_items')
    # ### end Alembic commands ###
