"""job runs

Revision ID: 54ac86ee0748
Revises: 7c1407a5008b
Create Date: 2026-02-10 13:18:29.220320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ac86ee0748'
down_revision: Union[str, Sequence[str], None] = '7c1407a5008b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('rq_job_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rq_job_id')
    )
    op.create_index(op.f('ix_job_runs_idempotency_key'), 'job_runs', ['idempotency_key'], unique=False)
    op.create_index('ix_job_runs_tenant_created', 'job_runs', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_job_runs_tenant_id'), 'job_runs', ['tenant_id'], unique=False)
    op.create_index('ix_job_runs_tenant_type_created', 'job_runs', ['tenant_id', 'job_type', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_runs_tenant_type_created', table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_tenant_id'), table_name='job_runs')
    op.drop_index('ix_job_runs_tenant_created', table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_idempotency_key'), table_name='job_runs')
    op.drop_table('job_runs')
    # ### end Alembic commands ###
