"""evidence metadata

Revision ID: cc805d395fee
Revises: 06b0821216ab
Create Date: 2026-02-10 14:57:31.224456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc805d395fee'
down_revision: Union[str, Sequence[str], None] = '06b0821216ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('evidence_items', sa.Column('original_filename', sa.String(length=512), nullable=True))
    op.add_column('evidence_items', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_runs', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('memberships', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'uploaded_at')
    op.drop_column('tenants', 'uploaded_at')
    op.drop_column('subscriptions', 'uploaded_at')
    op.drop_column('memberships', 'uploaded_at')
    op.drop_column('job_runs', 'uploaded_at')
    op.drop_column('evidence_items', 'uploaded_at')
    op.drop_column('evidence_items', 'original_filename')
    op.drop_column('audit_events', 'uploaded_at')
    # ### end Alembic commands ###
